[versions]
androidxCore = "1.9.0"
androidxFragment = "1.5.5"
material = "1.7.0"
lottie = "5.2.0"

[libraries]
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidxFragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidxMaterial = { module = "com.google.android.material:material", version.ref = "material" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
